# Ejecución del Script principal (Paso 3)
      - name: Ejecutar la App de Contenido
        run: python scripts/automation_app.py
        env:
          # Clave de OpenAI (Causa del error 401 si el valor es incorrecto o no se inyecta)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
          # Claves de Reddit (Estas líneas FALTABAN O ESTABAN INCOMPLETAS)
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}

      - name: Commit y Push del Nuevo Artículo
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add posts/
          git commit -m "feat: Articulo semanal generado via IA"
          git push
        if: success()
